build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.19
  amd64: ghcr.io/home-assistant/amd64-base:3.19
labels:
  org.opencontainers.image.title: "SMS Gammu Gateway (PavelVe Test)"
  org.opencontainers.image.description: "TEST VERSION - PavelVe's SMS Gammu Gateway for testing"
  org.opencontainers.image.source: "https://github.com/BigThunderSR/ha-legacy-gsm-sms"
  org.opencontainers.image.authors: "BigThunderSR"
  org.opencontainers.image.licenses: "Apache-2.0"
args:
  TEMPIO_VERSION: "2021.09.0"