build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.22
  amd64: ghcr.io/home-assistant/amd64-base:3.22
labels:
  org.opencontainers.image.title: "GSM SMS Gateway Enhanced"
  org.opencontainers.image.description: "Enhanced SMS Gammu Gateway with network provider lookup and comprehensive diagnostics. Based on PavelVe's SMS Gammu Gateway."
  org.opencontainers.image.source: "https://github.com/BigThunderSR/ha-legacy-gsm-sms"
  org.opencontainers.image.authors: "BigThunderSR (based on PavelVe's work)"
  org.opencontainers.image.licenses: "Apache-2.0"
args:
  TEMPIO_VERSION: "2021.09.0"